###----------------GET ALL USERS AND POSTS-----------------

GET http://localhost:8080/api/setup/
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5YWIwYzE0ZWRiNzQ2NTY4MzUxMWQiLCJlbWFpbCI6IkFsZXhAdGVzdC5jb20iLCJpYXQiOjE2ODU2OTY1ODN9.5HjlCdKkFh85vi4vql9GC1hlzcjAEC7Bw8mng2b3dQg

###----------------CREATE AN ADMIN ---------------------

POST http://localhost:8080/api/setup/admin
Content-Type: application/json

{
    "name": "Alex",
    "email": "Alex@test.com",
    "password": "secret"
}


###----------------CREATE USER------------------------------

POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "name": "Violet",
    "email": "Violet@test.com",
    "password": "12345"
}

###----------------LOGIN PART------------------------------


POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "name": "Violet",
    "email": "Violet@test.com",
    "password": "qwer"
}

###----------------GET ONE POST------------------------------

GET http://localhost:8080/posts/
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc4ZmRmM2E4MDI2NTAwNzY2ODZjYzAiLCJlbWFpbCI6IkFsdmluQHRlc3QuY29tIiwiaWF0IjoxNjg1NjcwNDczfQ.lR5Vpe8ofKAR0EywkmVD_V6f-A6ZtCsXuOxKDs4fkt4


###----------------CREATE ONE POST------------------------------

POST http://localhost:8080/posts/
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NGIwNjFjYTcxZjY1NWMyOWM3MWIiLCJlbWFpbCI6IktldmluQHRlc3QuY29tIiwiaWF0IjoxNjg1Njg4NTcxfQ.D82uQfFg0ZK1I3rutXSZD0JWuWwV9GC-i0vP8bpn5-Q
Content-Type: application/json

{
    "name": "Kevin's Second Post",
    "content": "Today I did...."
}

###----------------DELETE ONE POST------------------------------

DELETE http://localhost:8080/posts/
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NTIyNzU2MGViMWRiODgzYzdmOTEiLCJlbWFpbCI6IkFsZXhAdGVzdC5jb20iLCJpYXQiOjE2ODU2ODgxMzh9.soY646evtcDJ0bB5UmwWFYhqAAyKke7VRjXuCi8xZ8k


###----------------UPDATE ONE POST------------------------------


PATCH http://localhost:8080/posts/64799139abe3b9498c08f932 
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NTIyNzU2MGViMWRiODgzYzdmOTEiLCJlbWFpbCI6IkFsZXhAdGVzdC5jb20iLCJpYXQiOjE2ODU2ODk2Nzh9.62ZrOjBFrtTh_uM1ZNxoFdmTyTiYoWVhB12Uoati2U0
Content-Type: application/json

{
    "name": "My ADMIN updated First post name"
}

###---------------GET ACCOUNT INFO-------------------------------

GET http://localhost:8080/account/
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NzFkMjIxZjQwMTY1NDA4NzI0NTQiLCJlbWFpbCI6IlZpb2xldEB0ZXN0LmNvbSIsImlhdCI6MTY4NTY5MzgxMX0.nYwSKaqQBOYdoXgXsXGRJ2FQac3Vu0AXWDDyJdyvuco



###---------------PATCH ACCOUNT INFO-------------------------------

PATCH  http://localhost:8080/account/update
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NzFkMjIxZjQwMTY1NDA4NzI0NTQiLCJlbWFpbCI6IlZpb2xldEB0ZXN0LmNvbSIsImlhdCI6MTY4NTczMjY2N30.5uu_XQe_cHcMlV23PccN9cuZ8aZ1TxAptjoj89XhCDM
Content-Type: application/json

{
    "password": "12345",
    "oldpassword": "qwer"
}

###----------------DELETE ONE USER------------------------------

DELETE http://localhost:8080/account/647e9b6d225c53e227d5619e
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5YWIwYzE0ZWRiNzQ2NTY4MzUxMWQiLCJlbWFpbCI6IkFsZXhAdGVzdC5jb20iLCJpYXQiOjE2ODU2OTY1ODN9.5HjlCdKkFh85vi4vql9GC1hlzcjAEC7Bw8mng2b3dQg

