###----------------GET ALL USERS AND POSTS----------------------

GET http://localhost:8080/api/setup/
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc4ZmRmM2E4MDI2NTAwNzY2ODZjYzAiLCJlbWFpbCI6IkFsdmluQHRlc3QuY29tIiwiaWF0IjoxNjg1NjcwNDczfQ.lR5Vpe8ofKAR0EywkmVD_V6f-A6ZtCsXuOxKDs4fkt4


###----------------CREATE AN ADMIN ---------------------

POST http://localhost:8080/api/setup/admin
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc4ZmRmM2E4MDI2NTAwNzY2ODZjYzAiLCJlbWFpbCI6IkFsdmluQHRlc3QuY29tIiwiaWF0IjoxNjg1NjcwNDczfQ.lR5Vpe8ofKAR0EywkmVD_V6f-A6ZtCsXuOxKDs4fkt4
Content-Type: application/json

{
    "name": "Alex",
    "email": "Alex@test.com",
    "password": "secret"
}


###----------------CREATE USER------------------------------

POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "name": "Violet",
    "email": "Violet@test.com",
    "password": "12345"
}

###----------------LOGIN PART------------------------------


POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "name": "Alex",
    "email": "Alex@test.com",
    "password": "secret"
}

###----------------GET POSTS------------------------------

GET http://localhost:8080/posts/647901b682252a443602e00f
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc4ZmRmM2E4MDI2NTAwNzY2ODZjYzAiLCJlbWFpbCI6IkFsdmluQHRlc3QuY29tIiwiaWF0IjoxNjg1NjcwNDczfQ.lR5Vpe8ofKAR0EywkmVD_V6f-A6ZtCsXuOxKDs4fkt4


###----------------CREATE ONE POST------------------------------

POST http://localhost:8080/posts/
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NzFkMjIxZjQwMTY1NDA4NzI0NTQiLCJlbWFpbCI6IlZpb2xldEB0ZXN0LmNvbSIsImlhdCI6MTY4NTY4MDYwOX0.Qwt6oBuMgvJjn6sjhJSaoI4XbNd3Uuz6pj8lR1DgWw0
Content-Type: application/json

{
    "name": "Violet's Second Post",
    "content": "Dear Diary....2"
}

###----------------DELETE ONE POST------------------------------

DELETE http://localhost:8080/posts/647974effec803460bee009e
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc5NTIyNzU2MGViMWRiODgzYzdmOTEiLCJlbWFpbCI6IkFsZXhAdGVzdC5jb20iLCJpYXQiOjE2ODU2ODgxMzh9.soY646evtcDJ0bB5UmwWFYhqAAyKke7VRjXuCi8xZ8k


###----------------UPDATE ONE POST------------------------------


PATCH http://localhost:8080/posts/6478f3561ef04eda403ae4db 
Content-Type: application/json

{
    "name": "My Second updated First post name"
}