GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/646683a1938d164bca0395de

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "name": "My Second Post",
    "userPostId": 21
}

###

DELETE http://localhost:3000/posts/64668a3bae5235924630f94c